// <auto-generated />
using System;
using MES.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MES.Server.Migrations
{
    [DbContext(typeof(ProjectdbContext))]
    partial class ProjectdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MES.Shared.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListItems")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ListItems = "None",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            ReadOnly = false
                        },
                        new
                        {
                            Id = 2,
                            ListItems = "None",
                            Name = "User",
                            NormalizedName = "USER",
                            ReadOnly = false
                        });
                });

            modelBuilder.Entity("MES.Shared.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PageNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Routes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedWorkCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("isDeleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MES.Shared.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("MES.Shared.Entities.Params", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Params");
                });

            modelBuilder.Entity("MES.Shared.Entities.WcList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.Property<string>("tla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("MES.Shared.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipmentImageId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ShipmentImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MES.Shared.Models.LoginUserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginDateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginUserDetails");
                });

            modelBuilder.Entity("MES.Shared.Models.Logindetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logindetails");
                });

            modelBuilder.Entity("MES.Shared.Models.MESWorkcenters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workcenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MESWorkcenters");
                });

            modelBuilder.Entity("MES.Shared.Models.Receiving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Receivings");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.Imagedata", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncomingImageId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IncomingImageId");

                    b.ToTable("Imagedatas");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.IncomingImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IncomingImages");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.IncomingInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddQty")
                        .HasColumnType("int");

                    b.Property<string>("Aligned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedKnife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxReceivedWithSaddles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeramicSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYBasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYCenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Len")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlasticSleaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorCategorization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaddlePartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandBlasting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirLeftJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirRightJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedgelockAlignmentMarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeldingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yRight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IncomingInspections");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.NewRotorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workcenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewRotorData");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.RotorGrindingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddQty")
                        .HasColumnType("int");

                    b.Property<string>("AdvancedSharpingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aligned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedKnife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxReceivedWithSaddles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentersLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentersRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeramicSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerImportance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelayReasonTracking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GrindingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrindingdataSubmitedByDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrindingdataSubmiteddBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYBasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYCenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMoveoutsideoperation")
                        .HasColumnType("bit");

                    b.Property<string>("Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Len")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlasticSleaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionSubmitBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductionSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReliefLand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorCategorization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDiaLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDiaRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaddlePartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandBlasting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmitedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TirLeftJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirRightJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToothFaceLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToothFaceRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisualChecks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedgelockAlignmentMarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeldingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workcenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yRight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RotorGrindingData");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.RotorGrindingSavedData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddQty")
                        .HasColumnType("int");

                    b.Property<string>("AdvancedSharpingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aligned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedKnife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxReceivedWithSaddles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentersLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentersRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeramicSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerImportance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DelayReasonTracking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GrindingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrindingdataSavedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrindingdataSavedByDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYBasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYCenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMoveoutsideoperation")
                        .HasColumnType("bit");

                    b.Property<string>("Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Len")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlasticSleaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionSubmitBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductionSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReliefLand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorCategorization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDiaLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDiaRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaddlePartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandBlasting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmitedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TirLeftJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirRightJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToothFaceLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToothFaceRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisualChecks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedgelockAlignmentMarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeldingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workcenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yRight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RotorGrindingSavedData");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.RotorProductionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddQty")
                        .HasColumnType("int");

                    b.Property<string>("AdvancedSharpingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aligned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedKnife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxReceivedWithSaddles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeramicSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerImportance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYBasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYCenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Len")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlasticSleaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionSubmitBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductionSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorCategorization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaddlePartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandBlasting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmitedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TirLeftJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirRightJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedgelockAlignmentMarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeldingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workcenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yRight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RotorProductionData");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.RotorProductionSavedData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddQty")
                        .HasColumnType("int");

                    b.Property<string>("AdvancedSharpingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aligned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedKnife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxReceivedWithSaddles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeramicSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerImportance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYBasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYCenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Len")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlasticSleaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionSavedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductionSavedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorCategorization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaddlePartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandBlasting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmitedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TirLeftJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirRightJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedgelockAlignmentMarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeldingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workcenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yRight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RotorProductionSavedData");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.RotorSalesData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddQty")
                        .HasColumnType("int");

                    b.Property<string>("Aligned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedKnife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxReceivedWithSaddles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeramicSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerImportance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYBasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYCenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Len")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlasticSleaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorCategorization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaddlePartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandBlasting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmitedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TirLeftJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirRightJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedgelockAlignmentMarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeldingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yRight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RotorSalesData");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.RotorSalesSavedData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddQty")
                        .HasColumnType("int");

                    b.Property<string>("Aligned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bearing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingRemoved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BearingSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedKnife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoxReceivedWithSaddles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeramicSeals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerImportance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYBasicSharpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfYCenterGrinding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Left")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Len")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Others")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlasticSleaves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Right")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorCategorization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RotorsNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaddlePartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SandBlasting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SavedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SavedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TirLeftJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TirRightJournal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Top")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedgelockAlignmentMarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeldingNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yLeft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yRight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RotorSalesSavedData");
                });

            modelBuilder.Entity("MES.Shared.Models.ShipmentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipmentImage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MES.Shared.Entities.AppUserRole", b =>
                {
                    b.HasOne("MES.Shared.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MES.Shared.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MES.Shared.Models.Image", b =>
                {
                    b.HasOne("MES.Shared.Models.ShipmentImage", "ShipmentImage")
                        .WithMany("Images")
                        .HasForeignKey("ShipmentImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentImage");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.Imagedata", b =>
                {
                    b.HasOne("MES.Shared.Models.Rotors.IncomingImages", "IncomingImages")
                        .WithMany("Images")
                        .HasForeignKey("IncomingImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomingImages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("MES.Shared.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MES.Shared.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MES.Shared.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MES.Shared.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MES.Shared.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MES.Shared.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MES.Shared.Models.Rotors.IncomingImages", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MES.Shared.Models.ShipmentImage", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
